#!/bin/bash

# Script để commit các file còn lại (config, docs, tests, etc.)

echo "=== Committing Remaining Files ==="
echo ""

# 1. Configuration files
echo "1. Configuration Files..."
git add .fvmrc
git add devtools_options.yaml
if [ -n "$(git diff --cached --name-only)" ]; then
    git commit -m "chore: add FVM and DevTools configuration

- Add .fvmrc for Flutter version management
- Add devtools_options.yaml for DevTools settings"
    echo "  ✓ Committed Configuration"
else
    echo "  ⊘ No changes for Configuration"
fi
echo ""

# 2. Test files
echo "2. Test Files..."
if [ -d "test" ] && [ -n "$(find test -name '*.dart' 2>/dev/null)" ]; then
    git add test/
    if [ -n "$(git diff --cached --name-only)" ]; then
        git commit -m "test: add test files

- Add widget tests
- Setup test structure"
        echo "  ✓ Committed Test Files"
    else
        echo "  ⊘ No changes for Test Files"
    fi
else
    echo "  ⊘ No test files found"
fi
echo ""

# 3. Documentation and Scripts
echo "3. Documentation and Scripts..."
git add *.md
git add *.sh
if [ -n "$(git diff --cached --name-only)" ]; then
    git commit -m "docs: add documentation and commit scripts

- Add BUILD_INSTRUCTIONS.md
- Add CHANGELOG.md
- Add COMMIT_GUIDE.md
- Add QUICK_COMMIT.md
- Add GITIGNORE_GUIDE.md
- Add commit scripts for feature-based commits"
    echo "  ✓ Committed Documentation"
else
    echo "  ⊘ No changes for Documentation"
fi
echo ""

# 4. Generated Localization Files (optional)
echo "4. Generated Localization Files..."
read -p "Do you want to commit generated localization files? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    git add lib/l10n/app_localizations*.dart
    if [ -n "$(git diff --cached --name-only)" ]; then
        git commit -m "chore: add generated localization files

- Add generated app_localizations.dart files
- These files are auto-generated by flutter gen-l10n"
        echo "  ✓ Committed Generated Localization Files"
    else
        echo "  ⊘ No changes for Generated Localization Files"
    fi
else
    echo "  ⊘ Skipped Generated Localization Files (will be ignored)"
    # Add to .gitignore if not already there
    if ! grep -q "app_localizations.*\.dart" .gitignore; then
        echo "" >> .gitignore
        echo "# Generated localization files" >> .gitignore
        echo "lib/l10n/app_localizations*.dart" >> .gitignore
        echo "  ✓ Added to .gitignore"
    fi
fi
echo ""

# 5. Update .gitignore
echo "5. Update .gitignore..."
git add .gitignore
if [ -n "$(git diff --cached --name-only)" ]; then
    git commit -m "chore: update .gitignore

- Ignore build artifacts (android/app/.cxx/, ios/build/)
- Ignore VS Code personal settings
- Add comments for generated localization files"
    echo "  ✓ Committed .gitignore"
else
    echo "  ⊘ No changes for .gitignore"
fi
echo ""

echo "=== Done! ==="
echo "Run 'git status' to see remaining files"
echo "Run 'git log --oneline -10' to see commits"
