// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6EnItyhA_7-b7B0wcW8ahGa0pBH7uRA',
    appId: '1:15869935347:web:23f7f7227c451e9fabc186',
    messagingSenderId: '15869935347',
    projectId: 'ai-analyzer-b3def',
    authDomain: 'ai-analyzer-b3def.firebaseapp.com',
    storageBucket: 'ai-analyzer-b3def.appspot.com',
    measurementId: 'G-9GDVQTHQGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLUjDtHuGn7IYT4KBNB3iZc_Bpj6XqYcM',
    appId: '1:15869935347:android:5915e87ad78497b3abc186',
    messagingSenderId: '15869935347',
    projectId: 'ai-analyzer-b3def',
    storageBucket: 'ai-analyzer-b3def.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMbW8mSq0Zif59I7gWEeoPBaotNUCoH1c',
    appId: '1:15869935347:ios:50ae80ab9b325e9cabc186',
    messagingSenderId: '15869935347',
    projectId: 'ai-analyzer-b3def',
    storageBucket: 'ai-analyzer-b3def.appspot.com',
    iosBundleId: 'com.example.flutterAiAnalyzerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMbW8mSq0Zif59I7gWEeoPBaotNUCoH1c',
    appId: '1:15869935347:ios:50ae80ab9b325e9cabc186',
    messagingSenderId: '15869935347',
    projectId: 'ai-analyzer-b3def',
    storageBucket: 'ai-analyzer-b3def.appspot.com',
    iosBundleId: 'com.example.flutterAiAnalyzerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu6EnItyhA_7-b7B0wcW8ahGa0pBH7uRA',
    appId: '1:15869935347:web:d2a2cff5ea011488abc186',
    messagingSenderId: '15869935347',
    projectId: 'ai-analyzer-b3def',
    authDomain: 'ai-analyzer-b3def.firebaseapp.com',
    storageBucket: 'ai-analyzer-b3def.appspot.com',
    measurementId: 'G-ZCHS4B9ZYK',
  );
}
